config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :wiki_posts
  namespace :wiki_posts do
    get 'example'
  end
  namespace :welcome do
    get 'index'
    get 'about'
    get 'archive'
  end

  namespace :api do
    namespace :v1 do
      get 'wiki_posts/xml', to: 'wiki_posts#xml_index'
      get 'wiki_posts/csv', to: 'wiki_posts#csv_index'
      resources :wiki_posts
    end
    namespace :v2 do
      resources :wiki_posts
    end
  end

  get '/about', to: redirect('/welcome/about')
  root 'welcome#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/wiki_post.rb
# frozen_string_literal: true

class WikiPost < ApplicationRecord
  has_one_attached :image

  scope :all_visible, -> { where(hidden: false) }

  scope :search, ->(keyword) { where('title LIKE ?', "%#{keyword}%") if keyword.present? }

  scope :contributors, -> { pluck(:author).uniq }
end

app/controllers/api/v1/wiki_posts_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class WikiPostsController < ApplicationController
      include Api::V1::WikiPostsHelper
      require 'csv'

      before_action :parse_and_validate_json_request, only: [:create]

      def index
        @wiki_posts = paginate(WikiPost.all)

        render json: @wiki_posts
      end

      def show
        wiki_post = WikiPost.find(params[:id])
        decorated_wiki_post = WikiPostDecorator.new(wiki_post)
        render json: {
          upcased_title: decorated_wiki_post.upcased_title,
          short_description: decorated_wiki_post.short_description,
          formatted_date: decorated_wiki_post.formatted_date
        }
      end

      def create
        # create a wikipost from params in the request body. Render error if failure.
        @wiki_post = WikiPost.new(wiki_post_params)

        if @wiki_post.save
          render json: @wiki_post, status: :created
        else
          render json: @eiki_post.errors, status: :unprocessable_entity
        end
      end

      def update
        # finds the wikipost to update with parameters from request body. Render error if failure.
        @wiki_post = WikiPost.find(params[:id])

        if @wiki_post.update(wiki_post_params)
          render json: @wiki_post
        else
          render json: @wiki_post.errors, status: :unprocessable_entity
        end
      end

      def destroy
        # destroys a wiki post wth the provided id
        @wiki_post = WikiPost.find(params[:id])
        @wiki_post.destroy
        head :no_content
      end

      def xml_index
        @wiki_posts = WikiPost.all
        render xml: @wiki_posts
      end

      def csv_index
        @wiki_posts = WikiPost.all
        csv_data = WikiPostCsvGenerator.new(@wiki_posts).generate_csv

        send_data csv_data, filename: 'wiki_posts.csv', type: 'text/csv'
      end

      private

      def paginate(scope)
        page = params.fetch(:page).to_i
        limit = params.fetch(:limit).to_i

        scope.limit(limit).offset((page - 1) * limit)
      end

      def wiki_post_params
        params.permit(:title, :description, :author)
      end
    end
  end
end

app/controllers/api/v2/wiki_posts_controller.rb
# frozen_string_literal: true

module Api
  module V2
    class WikiPostsController < ApplicationController
      def index
        render json: { 'message': 'under construction!' }
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ErrorHandling
end

app/controllers/concerns/error_handling.rb
# frozen_string_literal: true

module ErrorHandling
  extend ActiveSupport::Concern
  included do
    rescue_from StandardError do |exception|
      respond_to_error(exception)
    end
  end

  private

  def respond_to_error(exception)
    respond_to do |format|
      format.html { render 'error/standard_error', status: :internal_server_error, locals: { exception: exception } }

      format.json { render json: { error: exception.message }, status: :internal_server_error }
    end
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end

  def about
    @wiki_posts = WikiPost.all
  end
end

app/controllers/wiki_posts_controller.rb
# frozen_string_literal: true

class WikiPostsController < ApplicationController
  include Factories
  before_action :set_wiki_post, only: %i[show edit update destroy]

  # GET /wiki_posts or /wiki_posts.json
  def index
    @wiki_posts = if params[:keyword].present?
                    WikiPost.search(params[:keyword])
                  else
                    WikiPost.all_visible
                  end
  end

  # GET /wiki_posts/1 or /wiki_posts/1.json
  def show
    respond_to do |format|
      format.html do
        # use the htmlrendering strategy
        html_renderer = RenderingStrategies::HtmlRendering.new
        render html: html_renderer.render(@wiki_post).html_safe
      end
      format.text do
        # use the plaintextrendering strategy
        text_renderer = RenderingStrategies::PlainTextRendering.new
        render plain: text_renderer.render(@wiki_post)
      end
    end
  end

  def example; end

  # GET /wiki_posts/new
  def new
    @wiki_post = WikiPost.new
  end

  # GET /wiki_posts/1/edit
  def edit; end

  # POST /wiki_posts or /wiki_posts.json
  def create
    is_hidden = wiki_post_params.delete(:hidden) == '1'

    @wiki_post = if is_hidden
                   WikiPostFactory.create_hidden(wiki_post_params)
                 else
                   WikiPostFactory.create_visible(wiki_post_params)
                 end

    respond_to do |format|
      if @wiki_post.save
        format.html { redirect_to wiki_post_url(@wiki_post), notice: 'Wiki post was successfully created.' }
        format.json { render :show, status: :created, location: @wiki_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wiki_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wiki_posts/1 or /wiki_posts/1.json
  def update
    respond_to do |format|
      if @wiki_post.update(wiki_post_params)
        format.html { redirect_to wiki_post_url(@wiki_post), notice: 'Wiki post was successfully updated.' }
        format.json { render :show, status: :ok, location: @wiki_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wiki_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wiki_posts/1 or /wiki_posts/1.json
  def destroy
    @wiki_post.destroy

    respond_to do |format|
      format.html { redirect_to wiki_posts_url, notice: 'Wiki post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_wiki_post
    @wiki_post = WikiPost.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def wiki_post_params
    params.fetch(:wiki_post, {}).permit(:title, :description, :author, :image, :hidden, :keyword)
  end
end

app/helpers/api/v1/wiki_posts_helper.rb
# frozen_string_literal: true

module Api
  module V1
    module WikiPostsHelper
      def parse_and_validate_json_request
        JSON.parse(request.body.read)
        request.body.rewind
      rescue JSON::ParserError => e
        render json: { error: "Malformed JSON: #{e.message}" }, status: :bad_request
      end
    end
  end
end

app/helpers/api/v2/wiki_posts_helper.rb
# frozen_string_literal: true

module Api
  module V2
    module WikiPostsHelper
      def do_something
        # When included in a class, this code becomes part of the class's instance methods.
        # It can be called on instances of the class.
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def display_contributors(contributors)
    content_tag(:ul) do
      contributors.compact.each do |contributor|
        concat(content_tag(:li, contributor.titleize))
      end
    end
  end
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/helpers/wiki_posts_helper.rb
# frozen_string_literal: true

module WikiPostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= javascript_importmap_tags %>
    <%= turbo_include_tags %>


    <title>WikiApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
`

app/views/welcome/about.html.erb
<h1>Wiki</h1>
<h2>Site contributors: </h2>
<%= display_contributors(@wiki_posts.contributors) %>

app/views/welcome/index.html.erb
<h1>My Wiki</h1>
<h2><%= link_to 'View Posts', wiki_posts_path %></h2>
<h2><%= link_to "About", welcome_about_path%></h2>

app/views/wiki_posts/_back_to_wikiposts.html.erb
<div>
    <%= link_to "Back to Wiki Posts", wiki_posts_path %>
</div>

app/views/wiki_posts/_form.html.erb
<%= form_with(model: wiki_post) do |form| %>
  <% if wiki_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wiki_post.errors.count, "error") %> prohibited this wiki_post from being saved:</h2>

      <ul>
        <% wiki_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wiki_posts/_wiki_post.html.erb
<div id="<%= dom_id wiki_post %>">
</div>

app/views/wiki_posts/edit.html.erb
<h1>Editing wiki post</h1>

<%= form_with model: @wiki_post, local: true do |form| %>

  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.submit "Edit" %>
  </div>
<% end %>
<br>

<div>
  <%= link_to "Show this wiki post", @wiki_post %> |
  <%= render 'wiki_posts/back_to_wikiposts' %>
</div>

app/views/wiki_posts/example.html.erb
<h1 class="title" > Wiki Page Title </h1>

<p class="description">  Wiki Page Body</p>

<div class="meta">
  <span class="author"> Wiki Page Author </span>
  <span class="creation"> Wiki Page Creation Date </span>
  <span class="update"> Wiki Last Update Date </span>

</div>

app/views/wiki_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Wiki Posts</h1>
<%= form_with(url: wiki_posts_path, method: :get, local: true) do |form| %>
  <%= form.label :keyword, 'Search:' %>
  <%= form.text_field :keyword%>
  <%= form.submit 'Search'%>
<%end%>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Created at</th>
      <th>Updated at</th>
    </tr>
  </thead>
  <tbody>
    <% @wiki_posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, wiki_post_path(post) %></td>
        <td><%= post.created_at.strftime('%B %d, %Y') %></td>
        <td><%= post.updated_at.strftime('%B %d, %Y') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Site contributors: </h2>
<ul>
  <% @wiki_posts.contributors.compact.each do |contributor| %>
    <li><%= contributor.titleize %></li>
  <% end %>
</ul>


<%= link_to "New wiki post", new_wiki_post_path %>

app/views/wiki_posts/new.html.erb
<h1>New wiki post</h1>

<%= form_with model: @wiki_post, local: true do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </div>

  <!-- Add hidden checkbox here -->
  <div class="field">
    <%= form.label :hidden, 'Hidden?' %><br>
    <%= form.check_box :hidden %>
  </div>

  <div>
    <%= form.submit "Create" %>
  </div>
<% end %>

<br>

<div>
  <%= render 'wiki_posts/back_to_wikiposts' %>
</div>

app/views/wiki_posts/show.html.erb
<p style="color: green"><%= notice %></p>



<h1><%= wiki_post.title.titleize %></h1>
<p>Created on <%= wiki_post.created_at.strftime('%B %d, %Y') %></p>
<p>Description: <%= wiki_post.description %></p>
<p>Author: <%=wiki_post.author.titleize %><p>
<p>Hidden?: <%=wiki_post.hidden %><p>


<% if wiki_post.image.attached? %>
  <%= image_tag wiki_post.image %>
<% end %>


<div>
  <%= link_to "Edit this wiki post", edit_wiki_post_path(wiki_post) %> |
  <%= render 'wiki_posts/back_to_wikiposts' %>

  <%= button_to "Delete", wiki_post, method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete #wiki_post.title}?" } } %>
</div>